<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="8" total="9" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="111727" started-at="2019-10-28T15:54:05 IST" finished-at="2019-10-28T15:55:56 IST">
    <groups>
    </groups>
    <test name="ContactsPageTest" duration-ms="111727" started-at="2019-10-28T15:54:05 IST" finished-at="2019-10-28T15:55:56 IST">
      <class name="GT.GT.RestApiTest">
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String)[pri:0, instance:GT.GT.RestApiTest@3d921e20]" name="setup" is-config="true" duration-ms="11121" started-at="2019-10-28T15:54:05 IST" finished-at="2019-10-28T15:54:16 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[restUrl]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyCallFunctionality()[pri:0, instance:GT.GT.RestApiTest@3d921e20]" name="verifyCallFunctionality" duration-ms="70896" started-at="2019-10-28T15:54:16 IST" finished-at="2019-10-28T15:55:27 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ON CALL] but found [dialing]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ON CALL] but found [dialing]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at GT.GT.RestApiTest.verifyCallFunctionality(RestApiTest.java:185)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCallFunctionality -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:GT.GT.RestApiTest@3d921e20]" name="tearDown" is-config="true" duration-ms="29060" started-at="2019-10-28T15:55:27 IST" finished-at="2019-10-28T15:55:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyCallFunctionality status=FAILURE method=RestApiTest.verifyCallFunctionality()[pri:0, instance:GT.GT.RestApiTest@3d921e20] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="closeBrowser1(java.lang.String)[pri:0, instance:GT.GT.RestApiTest@3d921e20]" name="closeBrowser1" is-config="true" duration-ms="628" started-at="2019-10-28T15:55:56 IST" finished-at="2019-10-28T15:55:56 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser1 -->
      </class> <!-- GT.GT.RestApiTest -->
    </test> <!-- ContactsPageTest -->
  </suite> <!-- TestSuite -->
</testng-results>
