<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-5HEF6VE" name="GT.GT.ContactsPageTest" tests="9" failures="1" timestamp="04 Jul 2019 09:59:37 GMT" time="450.447" errors="0">
  <testcase name="verifyCreateListFromContactsPageUsingPlusSymbol" time="45.981" classname="GT.GT.ContactsPageTest"/>
  <testcase name="verifyDeleteListFromContactsPage" time="46.353" classname="GT.GT.ContactsPageTest"/>
  <testcase name="verifyDeleteAddedContactsFromAddContactsTabOnOverlay" time="50.217" classname="GT.GT.ContactsPageTest"/>
  <testcase name="verifyCreateListFromExcelUpload" time="70.399" classname="GT.GT.ContactsPageTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at GT.GT.ContactsPageTest.verifyCreateListFromExcelUpload(ContactsPageTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCreateListFromExcelUpload -->
  <testcase name="verifyAddContactsFromWebListsTabOnOverlay" time="50.236" classname="GT.GT.ContactsPageTest"/>
  <testcase name="verifyAddContactsFromMobileContactsTabOnOverlay" time="50.085" classname="GT.GT.ContactsPageTest"/>
  <testcase name="verifyReNameListFromContactsPage" time="44.821" classname="GT.GT.ContactsPageTest"/>
  <testcase name="verifyCreateListFromContactsPage" time="42.759" classname="GT.GT.ContactsPageTest"/>
  <testcase name="verifyAddContactsFromAddContactsTabOnOverlay" time="49.596" classname="GT.GT.ContactsPageTest"/>
</testsuite> <!-- GT.GT.ContactsPageTest -->
